<!DOCTYPE html>
<html>
<head>
    <title>Create</title>
	<script src="/js/script.js"></script>
</head>
<body>
    <textarea id="code_snippet" placeholder="// write your code here"></textarea>
    <br>
    Time restriction: <input id="time_restriction" type="text" value="0"/>
    <br>
    Views restriction: <input id="views_restriction" type="text" value="0"/>
    <br>
    <button id="send_snippet" type="submit" onclick="send()">Submit</button>
</body>
</html>